-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 01-Ago-2023 às 15:00
-- Versão do servidor: 10.4.27-MariaDB
-- versão do PHP: 8.2.0
CREATE database esporte;
use esporte;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `esporte`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `noticia`
--

CREATE TABLE `noticia` (
  `id` int(11) NOT NULL,
  `titulo` text NOT NULL,
  `conteudo` text NOT NULL,
  `data_publicacao` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Extraindo dados da tabela `noticia`
--

INSERT INTO `noticia` (`id`, `titulo`, `conteudo`, `data_publicacao`) VALUES
(1, 'SALTOS ORNAMENTAIS ', 'Saltos ornamentais, também conhecidos como saltos ou saltos sincronizados, são uma modalidade esportiva que combina habilidades acrobáticas, precisão e graça. Os competidores, geralmente chamados de saltadores, realizam uma série de saltos a partir de plataformas ou trampolins em piscinas, exibindo movimentos elegantes e complexos enquanto mergulham na água. \r\n\r\nOs saltos ornamentais têm uma longa história, remontando aos tempos da antiguidade, mas se tornaram uma disciplina esportiva reconhecida no final do século XIX. Atualmente, é um dos esportes mais emocionantes e visualmente atraentes nas Olimpíadas e em outros eventos esportivos internacionais. \r\n\r\nExistem duas principais categorias de saltos ornamentais: plataforma e trampolim. Na plataforma, os atletas realizam seus saltos de uma plataforma elevada, geralmente a 10 metros de altura. Já no trampolim, os saltadores pulam de uma mola elástica, que oferece impulso, podendo variar de 1 a 3 metros de altura. \r\n\r\nOs saltos ornamentais são avaliados por um painel de juízes com base na execução, grau de dificuldade e elementos artísticos dos movimentos. A precisão do mergulho, a entrada na água, a forma do corpo durante o salto e a sincronização (caso sejam saltos sincronizados) são alguns dos critérios considerados. \r\n\r\nAlém das categorias individuais, também há os saltos sincronizados, onde dois saltadores realizam seus movimentos em conjunto, buscando perfeita sincronia e harmonia durante o salto. \r\n\r\nOs atletas desse esporte precisam de força, flexibilidade, equilíbrio e coragem para executar os movimentos complexos e acrobáticos. O treinamento envolve prática rigorosa, aperfeiçoamento técnico, aquisição de novos saltos e a preparação física adequada para minimizar o risco de lesões. \r\n\r\nEm resumo, os saltos ornamentais são uma emocionante modalidade esportiva que combina acrobacias, arte e habilidades atléticas. Os atletas realizam saltos espetaculares a partir de plataformas ou trampolins, buscando impressionar os juízes e o público com sua elegância, precisão e graça ao mergulhar na água. \r\n\r\n ', '2023-08-01'),
(3, 'SALTOS COM VARA ', 'O salto com vara é uma modalidade esportiva que faz parte do atletismo. Nessa disciplina, os competidores, também conhecidos como saltadores, usam uma vara flexível para impulsionar-se sobre uma barra horizontal colocada em uma altura pré-determinada. O objetivo é ultrapassar a barra sem derrubá-la. \r\n\r\nO salto com vara requer uma combinação de força, velocidade, agilidade e técnica refinada. O atleta corre em uma pista de aproximação, segurando a vara com as mãos, e, ao atingir uma marca específica, planta a vara no solo para obter impulso e se elevar no ar. Durante o salto, os saltadores devem executar manobras complexas para ultrapassar a barra com êxito. \r\n\r\nUm dos elementos cruciais no salto com vara é a \"quebra\" ou \"dobramento\" da vara, onde a vara se flexiona sob o peso do saltador, armazenando energia para lançá-lo para cima. A habilidade do saltador em coordenar a corrida, a abordagem, a plantada e a ação durante o salto determina o sucesso na altura alcançada. \r\n\r\nOs competidores têm três tentativas para ultrapassar cada altura, e os que alcançam a maior altura possível são os vencedores. No caso de empates, os critérios de desempate são geralmente o menor número de falhas anteriores e a menor quantidade de tentativas utilizadas para passar as alturas. \r\n\r\nO salto com vara é um esporte emocionante de se assistir, principalmente devido à incrível capacidade dos atletas de superarem alturas impressionantes. Essa modalidade tem sido uma parte fundamental do atletismo olímpico e outros eventos esportivos internacionais, proporcionando momentos emocionantes e recordes memoráveis. \r\n\r\n ', '2023-08-01'),
(4, 'BADMINTON ', ' \r\nO badminton é um esporte de raquete que pode ser jogado em disputas individuais (simples) ou em duplas (duplas). O objetivo do jogo é acertar um volante, também conhecido como \"birdie\" ou \"peteca\", sobre uma rede, passando-o para o campo adversário, de modo que o oponente não consiga devolvê-lo dentro das linhas de quadra. \r\n\r\nO badminton é jogado em uma quadra retangular, dividida por uma rede ao meio. O objetivo é marcar pontos fazendo o volante tocar o chão no campo adversário ou forçando o oponente a cometer um erro. \r\n\r\nOs jogadores utilizam raquetes leves e ágeis para golpear o volante. O volante é feito de penas ou materiais sintéticos e possui uma base redonda com uma saia, que o torna aerodinamicamente estável durante o jogo. \r\n\r\nO jogo requer agilidade, velocidade, habilidade de reflexo e estratégia. Os jogadores devem estar preparados para se movimentar rapidamente pela quadra, realizar golpes precisos e antecipar as jogadas do oponente. \r\n\r\nO badminton é um esporte popular em muitos países, especialmente na Ásia e Europa, e é praticado em todos os níveis, desde recreativo até competições internacionais, como os Jogos Olímpicos e campeonatos mundiais. \r\n\r\nÉ uma modalidade esportiva que promove a saúde cardiovascular, agilidade, coordenação e resistência física. Além disso, o badminton é uma atividade social e divertida, adequada para todas as idades e níveis de habilidade. \r\n\r\nEm resumo, o badminton é um esporte de raquete jogado em uma quadra dividida por uma rede. Os jogadores golpeiam um volante com raquetes, tentando marcar pontos e superar seus oponentes. É uma atividade física popular que combina velocidade, agilidade e estratégia, e pode ser apreciada por pessoas de todas as idades e níveis de habilidade. ', '2023-08-01'),
(5, '   TIRO COM ARCO ', ' \r\n\r\n \r\nO tiro com arco é uma antiga modalidade esportiva e habilidade de caça, que se transformou em um esporte competitivo e olímpico. Nessa disciplina, os arqueiros utilizam arcos para lançar flechas em direção a um alvo posicionado a uma distância específica. \r\n\r\nO objetivo do tiro com arco é acertar o centro do alvo ou atingir a pontuação mais alta possível, que varia de acordo com a distância e o tipo de competição. Os alvos possuem anéis concêntricos, sendo o centro o ponto com maior pontuação e os anéis exteriores com valores menores. \r\n\r\nExistem diferentes estilos de tiro com arco, incluindo o tiro com arco recurvo e o tiro com arco composto, ambos com características distintas em relação ao design do arco e às técnicas de tiro. No arco recurvo, os atletas devem segurar o arco curvado com os braços, enquanto no arco composto, a força é reduzida através de um sistema de roldanas e cabos. \r\n\r\nO tiro com arco exige precisão, controle, concentração e técnica apurada dos praticantes. Os arqueiros devem aprender a lidar com variáveis como vento, luz, temperatura e ajustar sua mira de acordo com essas condições. \r\n\r\nEssa modalidade esportiva é praticada individualmente e em equipe. As competições podem envolver distâncias variadas e podem ser realizadas em ambientes internos e externos. Os Jogos Olímpicos são um dos principais eventos em que o tiro com arco é disputado. \r\n\r\nAlém de ser um esporte competitivo, o tiro com arco também é uma atividade recreativa popular, apreciada por pessoas de todas as idades ao redor do mundo. Ele oferece benefícios físicos, como o desenvolvimento da força dos músculos do braço e da postura, e também promove habilidades mentais, como foco, paciência e controle emocional. \r\n\r\nEm resumo, o tiro com arco é uma modalidade esportiva que envolve o uso de arcos para lançar flechas em alvos. Requer habilidades técnicas, precisão e concentração dos arqueiros para atingir o centro do alvo ou obter a maior pontuação possível. É praticado em competições individuais e em equipe, oferecendo benefícios físicos e mentais aos praticantes. Além disso, é uma atividade recreativa popular em todo o mundo. ', '2023-08-01'),
(6, '   JUDÔ ', ' \r\n\r\nO judô é uma arte marcial japonesa que foi desenvolvida no final do século XIX pelo mestre Jigoro Kano. Essa disciplina enfatiza a utilização eficiente da força e da energia para lançar ou imobilizar um oponente. O objetivo do judô é submeter o adversário ao controle total, aplicando técnicas específicas. \r\n\r\nOs praticantes de judô são chamados de judocas. Eles utilizam quimonos, conhecidos como judogis, durante as competições e treinamentos. O judô é praticado em um tatame, uma superfície acolchoada que protege os atletas durante as quedas e projeções. \r\n\r\nAs técnicas do judô são divididas em dois grupos principais: as técnicas de arremesso (nage-waza) e as técnicas de controle e imobilização (katame-waza). O objetivo dos arremessos é desequilibrar o oponente e projetá-lo ao solo, enquanto as técnicas de controle buscam imobilizar ou forçar a desistência do oponente através de chaves e estrangulamentos. \r\n\r\nO judô enfatiza o respeito, a disciplina e a autodisciplina. Além disso, promove o desenvolvimento físico e mental dos praticantes. O treinamento inclui exercícios de movimentação, técnicas de projeção e imobilização, além de simulações de combate conhecidas como \"randori\". \r\n\r\nO judô é praticado em competições individuais, com diversas categorias de peso e faixa etária. O objetivo do combate é marcar pontos aplicando técnicas válidas, como projeções ou imobilizações, ou forçar o oponente a desistir através de chaves ou estrangulamentos. \r\n\r\nO judô é um esporte olímpico desde os Jogos Olímpicos de Tóquio em 1964, e é amplamente praticado em todo o mundo. Além disso, seus princípios de autodomínio, respeito e espírito esportivo tornaram-no uma arte marcial popular para pessoas de todas as idades e nacionalidades. \r\n\r\nEm resumo, o judô é uma arte marcial japonesa que enfatiza o uso eficiente da força para projetar ou imobilizar o oponente. É praticado em um tatame com quimonos especiais e inclui técnicas de arremesso e controle. O judô promove valores como respeito, disciplina e autodomínio e é praticado em competições esportivas e como uma forma de treinamento físico e mental em todo o mundo. ', '2023-08-01'),
(7, '   RUGYB SEVENS ', 'O Rugby Sevens, também conhecido como Sevens ou Seven-a-side, é uma variante do rugby tradicional que possui equipes compostas por sete jogadores em vez de 15. Essa modalidade é jogada em um campo de dimensões regulares, mas com partidas mais curtas, geralmente com duração de apenas sete minutos por tempo. \r\n\r\nO objetivo do Rugby Sevens é o mesmo do rugby de 15 jogadores: avançar com a bola e atravessar a linha de gol adversária para marcar pontos. Os jogadores podem passar a bola para frente e correr com ela, mas o objetivo é alcançar a linha de gol adversária enquanto evitam os tackles dos oponentes. \r\n\r\nUma característica marcante do Rugby Sevens é a velocidade do jogo e o alto número de tentativas de pontuação. Com menos jogadores em campo, há mais espaço para corridas e ataques, tornando as partidas emocionantes e com maior quantidade de pontos marcados. \r\n\r\nO Rugby Sevens é uma modalidade que vem ganhando popularidade em todo o mundo, especialmente após sua inclusão nos Jogos Olímpicos a partir de 2016. Essa participação olímpica ampliou a visibilidade e o interesse pelo esporte. \r\n\r\nAlém dos Jogos Olímpicos, o Rugby Sevens é disputado em diversos torneios e campeonatos internacionais, como o Circuito Mundial de Rugby Sevens, que reúne equipes de diferentes países em etapas realizadas em vários continentes. \r\n\r\nOs atletas de Rugby Sevens devem ter excelente condicionamento físico, agilidade, velocidade e habilidades técnicas aprimoradas para competir em um jogo tão dinâmico e acelerado. \r\n\r\nEm resumo, o Rugby Sevens é uma variante do rugby tradicional, jogada com sete jogadores em vez de 15. O objetivo é avançar com a bola e marcar pontos atravessando a linha de gol adversária. As partidas são mais curtas e rápidas, tornando o jogo emocionante e com maior quantidade de tentativas de pontuação. Essa modalidade vem ganhando popularidade, especialmente após sua inclusão nos Jogos Olímpicos, e é disputada em torneios internacionais em todo o mundo. \r\n\r\n ', '2023-08-01'),
(8, 'HANDEBOL ', ' \r\nO handebol é um esporte coletivo que combina elementos do futebol, basquete e hóquei, jogado em uma quadra com duas equipes de sete jogadores cada. O objetivo do jogo é marcar gols arremessando uma bola no gol adversário, utilizando as mãos. \r\n\r\nAs partidas de handebol são divididas em dois tempos de 30 minutos cada, com um intervalo de 10 a 15 minutos entre eles. Os jogadores podem driblar, passar e arremessar a bola para marcar gols, mas devem fazê-lo dentro de um limite de tempo específico (tempo de posse de bola). \r\n\r\nA quadra de handebol possui uma área de gol e uma linha de 7 metros, onde são cobrados os tiros de 7 metros, como punições por infrações cometidas pela equipe adversária. \r\n\r\nO handebol é um esporte rápido e dinâmico, que requer habilidades físicas e técnicas, como agilidade, velocidade, precisão nos passes e arremessos, além de boa capacidade de defesa e ataque. \r\n\r\nAlém das partidas tradicionais, o handebol também pode ser jogado na modalidade de handebol de praia, com apenas quatro jogadores em cada equipe, em uma quadra de areia. \r\n\r\nO handebol é um esporte popular em muitos países e é amplamente praticado em níveis recreativos, escolares, universitários e profissionais. É um esporte olímpico e também possui campeonatos e competições internacionais de alto nível, como o Campeonato Mundial de Handebol e o Campeonato Europeu de Handebol. \r\n\r\nEm resumo, o handebol é um esporte coletivo jogado em uma quadra, onde duas equipes de sete jogadores buscam marcar gols arremessando a bola com as mãos no gol adversário. É um esporte rápido e dinâmico, que exige habilidades físicas e técnicas dos jogadores. É popular em muitos países e é praticado em níveis recreativos e competitivos em todo o mundo. ', '2023-08-01'),
(9, 'BASEBOL ', ' \r\nO beisebol é um esporte de equipe popular, especialmente nos Estados Unidos, Japão e outros países. O jogo envolve duas equipes, cada uma com nove jogadores em campo em um determinado momento. O objetivo do beisebol é marcar pontos, chamados de \"corridas\", avançando por quatro bases em um campo em formato de diamante. \r\n\r\nO beisebol é jogado em nove entradas, e cada entrada é dividida em duas partes: a defesa e o ataque. Na defesa, uma equipe posiciona seus jogadores em posições específicas para tentar eliminar os jogadores adversários. Na parte do ataque, a equipe tenta bater a bola e correr pelas bases para marcar corridas. \r\n\r\nO arremessador é o jogador que lança a bola em direção ao rebatedor adversário, e o rebatedor deve tentar acertar a bola com um taco e enviá-la para o campo. Os jogadores do time em ataque também podem avançar pelas bases quando a bola é rebatida e, assim, marcar pontos para sua equipe. \r\n\r\nO beisebol é um esporte que requer habilidades físicas e mentais, como coordenação, precisão, velocidade e tomada de decisões rápidas. É considerado um jogo estratégico, com equipes e treinadores utilizando táticas para obter vantagem sobre o adversário. \r\n\r\nO beisebol é muito apreciado pelos fãs, e as principais ligas profissionais, como a Major League Baseball (MLB) nos Estados Unidos e a Nippon Professional Baseball (NPB) no Japão, atraem grandes multidões aos estádios e têm uma base de fãs dedicados. \r\n\r\nAlém disso, o beisebol também é praticado em níveis amadores e escolares, proporcionando a oportunidade para jovens atletas desenvolverem suas habilidades e paixão pelo esporte. \r\n\r\nEm resumo, o beisebol é um esporte de equipe jogado em um campo em formato de diamante. Duas equipes competem para marcar pontos avançando por quatro bases após rebater a bola lançada pelo arremessador adversário. É um esporte estratégico e emocionante, apreciado por fãs em todo o mundo, com ligas profissionais e amadoras que oferecem oportunidades para jogadores de todos os níveis. ', '2023-08-01'),
(10, '   VOLEI DE PRAIA ', 'O beisebol é um esporte de equipe popular, especialmente nos Estados Unidos, Japão e outros países. O jogo envolve duas equipes, cada uma com nove jogadores em campo em um determinado momento. O objetivo do beisebol é marcar pontos, chamados de \"corridas\", avançando por quatro bases em um campo em formato de diamante. \r\n\r\nO beisebol é jogado em nove entradas, e cada entrada é dividida em duas partes: a defesa e o ataque. Na defesa, uma equipe posiciona seus jogadores em posições específicas para tentar eliminar os jogadores adversários. Na parte do ataque, a equipe tenta bater a bola e correr pelas bases para marcar corridas. \r\n\r\nO arremessador é o jogador que lança a bola em direção ao rebatedor adversário, e o rebatedor deve tentar acertar a bola com um taco e enviá-la para o campo. Os jogadores do time em ataque também podem avançar pelas bases quando a bola é rebatida e, assim, marcar pontos para sua equipe. \r\n\r\nO beisebol é um esporte que requer habilidades físicas e mentais, como coordenação, precisão, velocidade e tomada de decisões rápidas. É considerado um jogo estratégico, com equipes e treinadores utilizando táticas para obter vantagem sobre o adversário. \r\n\r\nO beisebol é muito apreciado pelos fãs, e as principais ligas profissionais, como a Major League Baseball (MLB) nos Estados Unidos e a Nippon Professional Baseball (NPB) no Japão, atraem grandes multidões aos estádios e têm uma base de fãs dedicados. \r\n\r\nAlém disso, o beisebol também é praticado em níveis amadores e escolares, proporcionando a oportunidade para jovens atletas desenvolverem suas habilidades e paixão pelo esporte. \r\n\r\nEm resumo, o beisebol é um esporte de equipe jogado em um campo em formato de diamante. Duas equipes competem para marcar pontos avançando por quatro bases após rebater a bola lançada pelo arremessador adversário. É um esporte estratégico e emocionante, apreciado por fãs em todo o mundo, com ligas profissionais e amadoras que oferecem oportunidades para jogadores de todos os níveis. ', '2023-08-01');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `noticia`
--
ALTER TABLE `noticia`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `noticia`
--
ALTER TABLE `noticia`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
